unit TU_CBLIFOSingle;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, U_CircularBufferLIFO, U_CBLIFOSingle;

type
  // Test methods for class TCBLIFOSingle
  TestTCBLIFOSingle = class(TTestCase)
  strict private
    FCBLIFOSingle: TCBLIFOSingle;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure CreatedEmpty;
    procedure ResetResultsEmpty;
    procedure AddingElementResultsOneElement;
    procedure AddingCapacityResultsFull;
    procedure AddingAboveCapacity;
  end;

implementation

const
  C_CAPACITY = 5;

procedure TestTCBLIFOSingle.SetUp;
begin
  FCBLIFOSingle := TCBLIFOSingle.Create(C_CAPACITY);
end;

procedure TestTCBLIFOSingle.TearDown;
begin
  FCBLIFOSingle.Free;
  FCBLIFOSingle := nil;
end;

procedure TestTCBLIFOSingle.AddingCapacityResultsFull;
var
  i : integer;
begin
  FCBLIFOSingle.Reset;
  for i := 0 to C_CAPACITY - 1 do
    FCBLIFOSingle.Add(i);
  CheckEquals(C_CAPACITY, FCBLIFOSingle.Inserted);
  CheckTrue(FCBLIFOSingle.Full);
  CheckEquals(4, FCBLIFOSingle[0], '0 element');
  CheckEquals(3, FCBLIFOSingle[1], '1 element');
  CheckEquals(2, FCBLIFOSingle[2], '2 element');
  CheckEquals(1, FCBLIFOSingle[3], '3 element');
  CheckEquals(0, FCBLIFOSingle[4], '4 element');
  CheckEquals(C_CAPACITY-1, FCBLIFOSingle.First, 'First element');
  CheckEquals(0, FCBLIFOSingle.Last, 'Last element');
end;

procedure TestTCBLIFOSingle.AddingAboveCapacity;
begin
  AddingCapacityResultsFull;
  FCBLIFOSingle.Add(10);
  CheckEquals(10, FCBLIFOSingle[0], '0 element');
  CheckEquals(4, FCBLIFOSingle[1], '1 element');
  CheckEquals(3, FCBLIFOSingle[2], '2 element');
  CheckEquals(2, FCBLIFOSingle[3], '3 element');
  CheckEquals(1, FCBLIFOSingle[4], '4 element');
  CheckEquals(10, FCBLIFOSingle.First, 'First element');
  CheckEquals(1, FCBLIFOSingle.Last, 'Last element');
end;

procedure TestTCBLIFOSingle.AddingElementResultsOneElement;
begin
  FCBLIFOSingle.Reset;
  FCBLIFOSingle.Add(1);
  CheckEquals(1, FCBLIFOSingle.Inserted);
  CheckFalse(FCBLIFOSingle.Full);
  CheckEquals(1, FCBLIFOSingle.First, 'First element');
end;

procedure TestTCBLIFOSingle.CreatedEmpty;
var
  o : TCBLIFOSingle;
begin
  o:=TCBLIFOSingle.Create(C_CAPACITY);
  CheckEquals(C_CAPACITY, o.Capacity);
  CheckFalse(o.Full);
  CheckEquals(0, o.Inserted);
  o.Free;
end;

procedure TestTCBLIFOSingle.ResetResultsEmpty;
begin
  AddingElementResultsOneElement;
  FCBLIFOSingle.Reset;
  CreatedEmpty;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCBLIFOSingle.Suite);
end.

