unit TU_CircularIndexer;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, U_CircularIndexer;
type
  // Test methods for class TCircularIndexer
  
  TestTCircularIndexer = class(TTestCase)
  strict private
    FCircularIndexer: TCircularIndexer;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure CreatedEmpty;
    procedure ResetResultsEmpty;
    procedure IncrementResultsOnePosFurther;
    procedure IncrementToLength;
    procedure IncrementAboveLengthResultsLoop;
    procedure IncrementAboveLengthInNextLoop;
  end;

implementation

const
  C_LENGTH = 4;

procedure TestTCircularIndexer.SetUp;
begin
  FCircularIndexer := TCircularIndexer.Create(C_LENGTH);
end;

procedure TestTCircularIndexer.TearDown;
begin
  FCircularIndexer.Free;
  FCircularIndexer := nil;
end;

procedure TestTCircularIndexer.ResetResultsEmpty;
begin
  FCircularIndexer.SetPosition(0);
  CheckEquals(C_LENGTH, FCircularIndexer.Length);
  CheckEquals(0, FCircularIndexer.Pos);
  CheckEquals(0, FCircularIndexer.LoopsCount);
end;

procedure TestTCircularIndexer.CreatedEmpty;
var
  o : TCircularIndexer;
begin
  o:=TCircularIndexer.Create(C_LENGTH);
  try
    CheckEquals(C_LENGTH, o.Length);
    CheckEquals(0, o.Pos);
    CheckEquals(0, o.LoopsCount);
  finally
    o.Free;
  end;
end;

procedure TestTCircularIndexer.IncrementResultsOnePosFurther;
begin
  ResetResultsEmpty;
  FCircularIndexer.Inc;
  CheckEquals(1, FCircularIndexer.Pos);
  CheckEquals(0, FCircularIndexer.LoopsCount);
end;

procedure TestTCircularIndexer.IncrementToLength;
var
  i : integer;
begin
  ResetResultsEmpty;
  for i := 0 to C_LENGTH - 2 do
    FCircularIndexer.Inc;
  CheckEquals(3, FCircularIndexer.Pos);
  CheckEquals(0, FCircularIndexer.LoopsCount);
end;

procedure TestTCircularIndexer.IncrementAboveLengthResultsLoop;
var
  i : integer;
begin
  ResetResultsEmpty;
  for i := 0 to C_LENGTH - 1 do
    FCircularIndexer.Inc;
  CheckEquals(0, FCircularIndexer.Pos);
  CheckEquals(1, FCircularIndexer.LoopsCount);
end;

procedure TestTCircularIndexer.IncrementAboveLengthInNextLoop;
var
  i : integer;
begin
  ResetResultsEmpty;
  for i := 0 to C_LENGTH do
    FCircularIndexer.Inc;
  CheckEquals(1, FCircularIndexer.Pos);
  CheckEquals(1, FCircularIndexer.LoopsCount);
end;


initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCircularIndexer.Suite);
end.

