unit TU_EMA2;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, U_EMA2, U_CBLIFOSingle;
type
  // Test methods for class TEMA2
  
  TestTEMA2 = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure CreatedEmpty;
    procedure AddingBelowDepthResultsEmpty;
//    procedure AddingDepthElements;
//    procedure AddingMoreDepthElements;
  end;

implementation

const
  C_DEPTH = 4;

procedure TestTEMA2.SetUp;
begin
//
end;

procedure TestTEMA2.TearDown;
begin
//
end;

procedure TestTEMA2.AddingBelowDepthResultsEmpty;
var
  o : TEMA2;
begin
  o:=TEMA2.Create(C_DEPTH);
  try
    o.Add(1);
    o.Add(2);
    CheckEquals(C_DEPTH, o.Depth);
    CheckEquals(2, o.TotalCnt);
    CheckEquals(0, o.Value);
    CheckEquals(0, o.LastValue);
  finally
    o.Free;
  end;
end;

//procedure TestTEMA2.AddingDepthElements;
//var
//  o : TEMA2;
//begin
//  o:=TEMA2.Create(C_DEPTH);
//  try
//    o.Add(1);
//    o.Add(2);
//    o.Add(3);
//    o.Add(4);
//    CheckEquals(C_DEPTH, o.Depth);
//    CheckEquals(4, o.TotalCnt);
//    CheckEquals(((1.0 + 2.0 + 3.0 + 4.0) / 4.0), o.Value);
//    CheckEquals(0, o.LastValue);
//  finally
//    o.Free;
//  end;
//end;

//procedure TestTEMA2.AddingMoreDepthElements;
//begin
//
//end;

procedure TestTEMA2.CreatedEmpty;
var
  o : TEMA2;
begin
  o:=TEMA2.Create(C_DEPTH);
  try
    CheckEquals(C_DEPTH, o.Depth);
    CheckEquals(0, o.TotalCnt);
    CheckEquals(0, o.Value);
    CheckEquals(0, o.LastValue);
  finally
    o.Free;
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTEMA2.Suite);
end.

