unit TU_SMA2;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, U_SMA2, U_CBLIFOSingle;
type
  // Test methods for class TSMA2
  
  TestTSMA2 = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure CreatedEmpty;
    procedure AddingBelowDepthResultsEmpty;
    procedure AddingDepthElements;
    procedure AddingMoreDepthElements;
  end;

implementation

const
  C_DEPTH = 4;

procedure TestTSMA2.SetUp;
begin
//
end;

procedure TestTSMA2.TearDown;
begin
//
end;

procedure TestTSMA2.AddingBelowDepthResultsEmpty;
var
  o : TSMA2;
begin
  o:=TSMA2.Create(C_DEPTH);
  try
    o.Add(1);
    o.Add(2);
    CheckEquals(C_DEPTH, o.Depth);
    CheckEquals(2, o.TotalCnt);
    CheckEquals(0, o.Value);
    CheckEquals(0, o.LastValue);
  finally
    o.Free;
  end;
end;

procedure TestTSMA2.AddingDepthElements;
var
  o : TSMA2;
begin
  o:=TSMA2.Create(C_DEPTH);
  try
    o.Add(1);
    o.Add(2);
    o.Add(3);
    o.Add(4);
    CheckEquals(C_DEPTH, o.Depth);
    CheckEquals(4, o.TotalCnt);
    CheckEquals(((1.0 + 2.0 + 3.0 + 4.0) / 4.0), o.Value);
    CheckEquals(0, o.LastValue);
  finally
    o.Free;
  end;
end;

procedure TestTSMA2.AddingMoreDepthElements;
var
  o : TSMA2;
begin
  o:=TSMA2.Create(C_DEPTH);
  try
    o.Add(1);
    o.Add(2);
    o.Add(3);
    o.Add(4);
    o.Add(5);
    CheckEquals(C_DEPTH, o.Depth);
    CheckEquals(5, o.TotalCnt);
    CheckEquals(((2.0 + 3.0 + 4.0 + 5.0) / 4.0), o.Value);
    CheckEquals(((1.0 + 2.0 + 3.0 + 4.0) / 4.0), o.LastValue);
  finally
    o.Free;
  end;
end;

procedure TestTSMA2.CreatedEmpty;
var
  o : TSMA2;
begin
  o:=TSMA2.Create(C_DEPTH);
  try
    CheckEquals(C_DEPTH, o.Depth);
    CheckEquals(0, o.TotalCnt);
    CheckEquals(0, o.Value);
    CheckEquals(0, o.LastValue);
  finally
    o.Free;
  end;  
end;


initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSMA2.Suite);
end.

